### ISSUE TITLE
Package parsing error

### ISSUE THREAD

**Issue by rajeshca911** [rareranger/ps4jbandroid#1]
Cant be installed in Samsung  S20

Device:  SM-G960F
OS : Android 12
![Screenshot_20220112-161203_Package installer](https://user-images.githubusercontent.com/97240423/149125327-855d5259-a0fd-4a57-8c8c-4ae5363af4c5.jpg)

**Comment by rareranger** [comment]
Try installing via ADB and check the exact reason why it wont install. I just tested on a Samsung Galaxy A12 and a Redmi Note 10 pro and it works fine.

**Comment by rajeshca911** [comment]
C:\Users\Raj\Desktop>adb install ps4jb.apk
Performing Streamed Install
adb: failed to install ps4jb.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl323070970.tmp/base.apk (at Binary XML file line #24): org.ktech.ps4jailbreak.MainActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]

**Comment by rajeshca911** [comment]
> Try installing via ADB and check the exact reason why it wont install. I just tested on a Samsung Galaxy A12 and a Redmi Note 10 pro and it works fine.


C:\Users\CA Rajesh\Desktop>adb install ps4jb.apk
Performing Streamed Install
adb: failed to install ps4jb.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl323070970.tmp/base.apk (at Binary XML file line #24): org.ktech.ps4jailbreak.MainActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]

**Comment by rareranger** [comment]
> 

I see the issue (https://medium.com/androiddevelopers/lets-be-explicit-about-our-intent-filters-c5dbe2dbdce0). I'll be fixing it and releasing a fixed version shortly.

**Comment by rareranger** [comment]
@rajeshca911  check if this version installs successfully and let me know. I don't have a device running Android 12 to test with.

https://github.com/rareranger/ps4jbandroid/releases/download/v1.1/ps4jb_v1.1.apk

**Comment by rajeshca911** [comment]
> @rajeshca911 check if this version installs successfully and let me know. I don't have a device running Android 12 to test with.
> 
> https://github.com/rareranger/ps4jbandroid/releases/download/v1.1/ps4jb_v1.1.apk

This one worked for me. And running correctly 
Cool 😎 & Thanks
