### ISSUE TITLE
Dark mode problem

### ISSUE THREAD

**Issue by Moodyne** [rareranger/ps4jbandroid#4]
Dark mode doest work well some text can't be seen.![Screenshot_20220115-151555_PS4 JailBreak.jpg](https://user-images.githubusercontent.com/97656352/149640710-86571fcc-97c4-4a53-942a-e5307a1d0040.jpg)

**Comment by rareranger** [comment]
I'll look into it for the next revision.

**Comment by rareranger** [comment]
@Moodyne what device are you using and what Android version? Dark mode works fine on my device. Are you using any themes or anything like that?

**Comment by rareranger** [comment]
@Moodyne Found the issue. Can you test this version and tell me if it works:

https://github.com/rareranger/ps4jbandroid/releases/download/v2.3/ps4jb_v2.3.apk

**Comment by Moodyne** [comment]
Tried on v2.3 still the same issue.

**Comment by rareranger** [comment]
What device are you using and which Android version are you running?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Moodyne** [comment]
I'm using a Galaxy Note9 running Android 10.

**Comment by rareranger** [comment]
@Moodyne  Try this one https://github.com/rareranger/ps4jbandroid/releases/download/v2.3.1/ps4jb_v2.3.1.apk

**Comment by Moodyne** [comment]
Thanks it works perfectly 😊
