### ISSUE TITLE
[improvement] app update notices or update from the app

### ISSUE THREAD

**Issue by eemcm2** [rareranger/ps4jbandroid#6]
Dear rareranger, I am very grateful for your work and for listening to all the suggestions.  the only thing that would be missing to be excellent, to implement some way to receive a notification or to be able to check updates directly from the app.

**Comment by rareranger** [comment]
I'll add that to the next revision. :+1:

**Comment by rareranger** [comment]
@eemcm2  Done.

https://github.com/rareranger/ps4jbandroid/releases/tag/v3.2
